### ISSUE TITLE
Consider removing duplicate default value and javadoc tags from configuration key's javadoc

### ISSUE THREAD

**Issue by snicoll** [akihyro/orika-spring-boot-starter#2]
The annotation processor does not handle javadoc tags and they are written as is in the json file. It's not a requirement for IDE to be able to parse this so the output may not be nice (I haven't tried though).

Also, please do not write "Defaults to XYZ" in the documentation since the default value is picked up by the initial value and IDE display that information when available already. If the metadata does not contain that value the `defaultValue` field in manual metadata is a much better option than in the description.

Thanks!

**Comment by akihyro** [comment]
I hadn't  considered the output of the annotation processor.
Thank you for pointing out the issue.

I fixed it as follows: a7d4b8e075b52f4d61656a5826599638f991a62e

* I removed Javadoc tags.
* I removed duplicate descriptions of default values from Javadoc comments.
* I decided not to use Optional.

If you are ok with this, I will release it as the next version!

**Comment by snicoll** [comment]
LGTM

**Comment by akihyro** [comment]
v1.4.0 has been released!

https://github.com/akihyro/orika-spring-boot-starter/releases/tag/v1.4.0
