### ISSUE TITLE
Compiling on Java 9 cause some issue

### ISSUE THREAD

**Issue by rakk** [akihyro/orika-spring-boot-starter#5]
The starter is working fine with project based on Spring Boot and Java 9.

But when tried to compile starter locally using ```mvn clean verify``` with Java 9 I got:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.0:jar (jar) on project orika-spring-boot-starter: MavenReportException: Error while generating Javadoc: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set. -> [Help 1]
[ERROR] 
```
Please add support for Java 9.

**Comment by akihyro** [comment]
Thanks for report.
I would like to add Java 9 support.
Please wait for the next version...

Thanks.

**Comment by akihyro** [comment]
I could compile on Java 9 on my machine.
The version of maven-javadoc-plugin seems to be different from mine.
Have you modified any source code?

This time, I added tests on Java 9, 10 to CircleCI (21d2bdc, d2fd9e7).
Also, I supported Spring Boot 2 in v1.8.0 (#7).

If you still have problems, please let us know.

Thanks.
